[package]
name = "hello_std"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
[dependencies]
Bridge = { git = "https://github.com/wtdcode/sui", rev = "bed1a2317f3f2fe2595d6f80767865a17363bf95", subdir = "crates/sui-framework/packages/bridge" }
MoveStdlib = { git = "https://github.com/wtdcode/sui", rev = "bed1a2317f3f2fe2595d6f80767865a17363bf95", subdir = "crates/sui-framework/packages/move-stdlib" }
Sui = { git = "https://github.com/wtdcode/sui", rev = "bed1a2317f3f2fe2595d6f80767865a17363bf95", subdir = "crates/sui-framework/packages/sui-framework" }
SuiSystem = { git = "https://github.com/wtdcode/sui", rev = "bed1a2317f3f2fe2595d6f80767865a17363bf95", subdir = "crates/sui-framework/packages/sui-system" }

[addresses]
[dev-dependencies]
[dev-addresses]
