name: Push to dockerhub

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull sources'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MOVY_DOCKER_USERNAME }}
          password: ${{ secrets.MOVY_DOCKER_PAT }}

      - name: Build and push
        if: "!startsWith(github.ref, 'refs/tags')"
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: movyrs/movy:latest
      
      - name: Build and push with github ref
        if: "startsWith(github.ref, 'refs/tags')"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            movyrs/movy:latest
            movyrs/movy:${{github.ref_name}}